Add two more methods
generate_dataset
get_dataset

Bug: Traceback (most recent call last):
  File "c:path\Python Project\DataSet.py", line 41, in <module>
    generator.generate_records()
TypeError: DataSet.generate_records() missing 1 required positional argument: 'record_id'